name: Aristeas NewUniversalUpload
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4.1.4
      - id: test_SEWT
        run: |
          & "C:\actions-runner\externals\testupload.ps1"
