name: Aristeas NewUniversalUpload
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4.1.4
      - id: test_SEWT
        run: |
          & "C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Bin64\SEWorkshopTool.exe" push --mods "C:\actions-runner\_work\SCModRepository\SCModRepository\Weapon Mods\Stable"
