name: Aristeas NewUniversalUpload
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
            separator: ','
      - name: Find Mods
        run: bash ModIdFinder.sh "${{ steps.changed-files.outputs.all_changed_files }}" >> $GITHUB_OUTPUT
      
      #- name: List all changed files
      #  env:
      #    ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      #  run: |
      #    for file in ${ALL_CHANGED_FILES}; do
      #      echo "$file was changed"
      #    done
      - id: test_SEWT
        run: |
          & "C:\actions-runner\externals\SC_NewUniversalUpload.exe" $GITHUB_OUTPUT
