name: Aristeas NewUniversalUpload
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - id: test
        run: echo "Test Doc" > TestDoc.txt
      - id: retrieve git files
      - uses: actions/checkout@v4.1.4
