name: "Upload AryxWeaponIndustriesMuzzMod"

on:
  push:
  branches:
      - "master"
    paths:
      - "AryxWeaponIndustriesMuzzMod/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 2659227392
          path: "AryxWeaponIndustriesMuzzMod"
          changelog: ${{ github.event.head_commit.message }}              
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
