name: "Upload Harmzone-Muzzmod"

on:
  push:
  branches:
      - "master"
    paths:
      - "Harmzone-Muzzmod/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 2890480337
          path: "Harmzone-Muzzmod"
          changelog: ${{ github.event.head_commit.message }}           
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
