name: "Upload Heavy-Assault-Systems"

on:
  push:
    paths:
      - "Heavy-Assault-Systems/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 3017853784
          path: "Heavy-Assault-Systems"
          changelog: ${{ github.event.head_commit.message }}            
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
