name: "Upload to REEECore-Dev"

on:
  push:
    paths:
      - "REEECore-Dev/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 3017853482
          path: REEECore-Dev
          changelog: ${{ github.event.head_commit.message }}
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
