name: "Upload Starcore Minimalist Hud"

on:
  push:
  branches:
      - "master"
    paths:
      - "Starcore Minimalist Hud/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 2846202563
          path: "Starcore Minimalist Hud"
          changelog: ${{ github.event.head_commit.message }}              
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
