name: Aristeas UniversalUpload
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
      - name: Get changed files
        id: changed-files
        run: |
            if ${{ github.event_name == 'pull_request' }}; then
                echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
            else
                echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
            fi
      - name: List changed files
        run: |
            for file in ${{ steps.changed-files.outputs.changed_files }}; do
                echo "$file was changed"
            done
      
      #- name: List all changed files
      #  env:
      #    ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      #  run: |
      #    for file in ${ALL_CHANGED_FILES}; do
      #      echo "$file was changed"
      #    done

      #- id: set-matrix
      #  run: bash ModIdFinder.sh "${{ steps.changed-files.outputs.changed_files }}" >> $GITHUB_OUTPUT
  
  workshop-upload:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0
          sparse-checkout: ${{ matrix.path }}
          
      - name: Delay
        run: sleep $((${{ strategy.job-index }} * 10))
        
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          login: true
          publishedFileID: ${{ matrix.value }}
          # path: ${{ matrix.path }}
          changelog: ${{ github.event.head_commit.message }}
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
